ipfs-rendezvous-experiment:
  build: ./
  restart: always
  ports:
    - "30333:30333"
    - "30334"
  environment:
    VIRTUAL_PORT: "30334"
    VIRTUAL_HOST: "bootstrap1.lab.metamask.io"
    LETSENCRYPT_HOST: "bootstrap1.lab.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
